name: Flutter Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      flutter-version: ${{ steps.set-version.outputs.flutter-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract Flutter version
        id: set-version
        run: |
          FLUTTER_VERSION=$(grep 'flutter:' pubspec.yaml -A 1 | tail -1 | awk '{print $2}' | tr -d '"')
          echo "flutter-version=${FLUTTER_VERSION:-3.16.9}" >> $GITHUB_OUTPUT

  android-apk:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
          channel: stable
          
      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Android APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  android-appbundle:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
          channel: stable
          
      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build AppBundle
        run: flutter build appbundle --release
      
      - name: Upload AppBundle
        uses: actions/upload-artifact@v4
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  linux-build:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
          channel: stable
          
      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Install packages
        run: flutter pub get
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Create artifact
        run: |
          mkdir -p artifacts/linux
          cp -r build/linux/release/bundle/* artifacts/linux/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: artifacts/linux/

  windows-build:
    needs: setup
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
          channel: stable
          
      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Create artifact
        run: |
          New-Item -ItemType Directory -Path artifacts/windows -Force
          Copy-Item -Path "build\windows\runner\Release\*" -Destination "artifacts\windows\" -Recurse
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: artifacts/windows/

  web-build:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
          channel: stable
          
      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web --release
      
      - name: Create artifact
        run: |
          mkdir -p artifacts/web
          cp -r build/web/* artifacts/web/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: artifacts/web/

  ios-build:
    needs: setup
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
          channel: stable
          
      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Create artifact
        run: |
          mkdir -p artifacts/ios
          cp -r build/ios/Release-iphoneos/* artifacts/ios/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: artifacts/ios/
